id: P70DD4B54
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA3JT13330
  instance_id: http://purl.bdrc.io/resource/IE3JT13330
  collection_id: http://purl.bdrc.io/resource/PR0ET001
  language_id: None
  title:
    bo:
    - མཆོད་རྟེན་གྱི་སྐོར་དང་། སཱཙྪ་གདབ་ཆོག། འོད་ཟེར་དྲི་མེད་ཀྱི་བཟླས་པ། གཙུག་ཏོར་དྲི་མེད་ཀྱི་གཟུངས་བཅས།
  alt_title:
    bo:
    - མཆོད་རྟེན་བརྒྱ་རྩ་བརྒྱད་གདབ་པའི་ཆོ་ག་དང་མཆོད་རྟེན་བསྐོར་བའི་ཚིགས་བཅད། གཙུག་ཏོར་དྲི་མ་མེད་པའི་གཟུངས་དང་འབྲེལ་བའི་སཱཙྪ་གདབ་པའི་ཆོ་ག
      འཕགས་པ་འོད་ཟེར་དྲི་མེད་ཀྱི་རྒྱུན་གྱི་བཟླས་པ་བྱ་ཚུལ། གཙུག་ཏོར་དྲི་མེད་གཟུངས་བཅས།
  author: None
  publisher: DharmaDownload
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    e983c1781cb64a5cba94cdc72cb2363c:
      title: ༄༅།་།གཙུག་ཏོར་དྲི་མ་མེད་པའི་གཟུངས་དང་འབྲེལ་བར་སཱཙྪ་གདབ་པའི་ཆོ་གའི་ལག་ལེན་དྲི་མེད་ཀུན་སྣང་ཞེས་བྱ་བ་བཞུགས་སོ།་།
      volume_number: 2
      base_file: UT3JT13330_002_0000.txt
      reference: http://purl.bdrc.io/resource/VL47F5360DB59317EA
      image_group: null
      quality: null
    c5bc23d9c1104c66bc738a7e1eaf7fdd:
      title: ༄༅།་།མཆོད་རྟེན་བསྐོར་བའི་ཚིགས་སུ་བཅད་པ་བཞུགས་སོ།་།
      volume_number: 4
      base_file: UT3JT13330_004_0000.txt
      reference: http://purl.bdrc.io/resource/VLA38D1534218F9502
      image_group: null
      quality: null
    c3dcff1cd1864b0dac71ab96d6784052:
      title: གཙུག་ཏོར་དྲི་མེད་གཟུངས་རིང་ནི།ན་མཿསརྦ་ཏཐཱ་ག་ཏཱ་ནཱཾ།ཨོཾ་མ་ཧཱ་ཙིནྟཱ་མ་ཎི་ཛྭ་ལ་ན་སཱ་ག་ར་གམྦྷཱིརེ།ཨཱ་ཀརྵ་ཡ།ཨཱ་ཀརྵ་ཡ།ཨཱ་ཡུནྡྷར།ཨཱ་ཡུན
      volume_number: 5
      base_file: UT3JT13330_005_0000.txt
      reference: http://purl.bdrc.io/resource/VLB33FE7EAA2C3B4CD
      image_group: null
      quality: null
    0f788103b2314ee5bef6a2dd1dd7c1b2:
      title: ༄༅།་།མཆོད་རྟེན་བརྒྱ་རྩ་བརྒྱད་གདབ་པའི་ཆོ་གའི་མཁན་ཆེན་ཞི་བ་འཚོས་མཛད་པ་ལས་ཉུང་ངུར་བསྡུས་པ་དྲི་མེད་ལམ་འཇུག་ཅེས་བྱ་བ་བཞུགས་སོ།་།
      volume_number: 1
      base_file: UT3JT13330_001_0000.txt
      reference: http://purl.bdrc.io/resource/VLE477C35A35558974
      image_group: null
      quality: null
    e9aecac6833c46fdaf8f6a457c286b3c:
      title: འཕགས་པ་འོད་ཟེར་དྲི་མེད་ཀྱི་རྒྱུན་གྱི་བཟླས་པ་བྱ་ཚུལ་འཆི་མེད་འབྱུང་བ་ཞེས་བྱ་བ་བཞུགས་སོ།་།ཚོགས་གཉིས་རྒྱ་མཚོའི་བཅུད་ལས་འཁྲུངས།་།ཐུ
      volume_number: 3
      base_file: UT3JT13330_003_0000.txt
      reference: http://purl.bdrc.io/resource/VLB8B382FC0B5E03E9
      image_group: null
      quality: null
  reproductionOf: []
created_at: '2021-12-22T11:22:15.134689'
last_modified_at: '2021-12-22T11:22:15.134703'
